apiVersion: v1
kind: Service
metadata:
  name: dss-api-service
  namespace: digital-social-score
  labels:
    app: dss-api
spec:
  type: ClusterIP
  selector:
    app: dss-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: dss-api-nodeport
  namespace: digital-social-score
  labels:
    app: dss-api
spec:
  type: NodePort
  selector:
    app: dss-api
  ports:
  - name: http
    port: 80
    targetPort: 8000
    nodePort: 30001
    protocol: TCP
